// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animation': string;
  'deleteBtn': string;
  'taskItem': string;
  'title': string;
  'wrapAction': string;
}
export const cssExports: CssExports;
export default cssExports;
